[font]
size = 12

[font.normal]
family = "Monospace"
style = "Regular"

[font.bold]
family = "Monospace"
style = "Bold"

[font.italic]
family = "Monospace"
style = "Italic"

[font.bold_italic]
family = "Monospace"
style = "Bold Italic"

# [general]
# import = ["~/.config/alacritty/themes/linux.toml"]

