"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false 

[character] # The name of the module we are configuring is 'character'
success_symbol = '[‚ùØ](bold green)'

[package]
disabled = false

[battery]
disabled = true
